# Generated by Django 6.0.2 on 2026-08-15 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0017_alter_subscription_end_date'),
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_departments', to='subscription.organisation'),
        ),
    ]
