# Generated by Django 6.0.2 on 2026-04-06 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='organization',
            new_name='organisation',
        ),
     
    ]
