# Generated by Django 6.0.2 on 2026-04-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_rename_organization_invoice_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_tasks_per_month',
            field=models.IntegerField(default=1000),
        ),
    ]
