# Generated by Django 6.0.2 on 2026-04-10 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionplan_max_tasks_per_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organisation/logos/'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organisation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisationmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
