# Generated by Django 6.0.2 on 2026-04-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_organisation_logo_alter_organisation_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='next_billing_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
