# Generated by Django 6.0.2 on 2026-04-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_subscription_next_billing_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Organisation', 'verbose_name_plural': 'Organisations'},
        ),
        migrations.AlterModelOptions(
            name='organisationmember',
            options={'ordering': ['-joined_at'], 'verbose_name': 'Organisation Member', 'verbose_name_plural': 'Organisation Members'},
        ),
    ]
