# Generated by Django 6.0.2 on 2026-07-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_tasks_per_month',
            field=models.IntegerField(default=100),
        ),
    ]
