# Generated by Django 6.0.2 on 2026-08-01 04:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_alter_subscriptionplan_max_tasks_per_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organisation',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_org_per_owner'),
        ),
    ]
