# Generated by Django 6.0.2 on 2026-08-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_subscriptionplan_razorpay_plan_id_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='razorpay_customer_id',
            field=models.CharField(blank=True, help_text="Razorpay's customer_id for this organisation.", max_length=255, null=True),
        ),
    ]
