# Generated by Django 6.0.2 on 2026-08-02 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 1, 10, 18, 10, 773176, tzinfo=datetime.timezone.utc)),
        ),
    ]
