# Generated by Django 6.0.2 on 2026-08-05 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_event_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 4, 5, 28, 46, 953048, tzinfo=datetime.timezone.utc)),
        ),
    ]
