# Generated by Django 6.0.2 on 2026-08-11 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_payment_razorpay_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, help_text='e.g. card, upi, netbanking', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='raw_response',
            field=models.JSONField(blank=True, help_text='Full webhook payload, kept for audits/disputes', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='initiated', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 10, 2, 50, 18, 28214, tzinfo=datetime.timezone.utc)),
        ),
    ]
