# Generated by Django 6.0.2 on 2026-08-15 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0016_alter_invitation_role_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 14, 6, 59, 0, 17029, tzinfo=datetime.timezone.utc)),
        ),
    ]
