# Generated by Django 6.0.2 on 2026-09-13 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0018_alter_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 10, 13, 14, 21, 33, 309221, tzinfo=datetime.timezone.utc)),
        ),
    ]
