# Generated by Django 6.0.2 on 2026-03-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_created_by_alter_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
    ]
